version: '3.9'

services:
  app:
    image: php:7.4-apache
    ports:
      - "8081:80"
    volumes:
      - ./app:/var/www/html
    depends_on:
      - db
    networks:
      - my_network

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: 172.17.0.3
      MYSQL_DATABASE: apimysql
      MYSQL_USER: root
      MYSQL_PASSWORD: 200501
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - my_network

networks:
  my_network:

volumes:
  db_data:
